(ql:quickload "cl-utilities")
(in-package :csharp-parser)

(defun variable? (tokenizer)
  (with-peek
    (or (match-assign peek) 
	(match-end peek))))

(defun make-variable (tokenizer node-stack enclosing-node-name)
  (if (not (variable? tokenizer))
      (print "error parsing variable"))
  (destructuring-bind (visibility-node type-node) (read-vis-type node-stack) 
    (let* ((name (current-token tokenizer))
	   (peek (peek-token tokenizer))
	   (value (if (match-assign peek)
		      (progn
			(advanze-token tokenizer)
			(parse-expression tokenizer))
		      (make-ast-node "variable-value" ())))
	   (variable-node (make-ast-node enclosing-node-name ())))
      (push-node visibility-node variable-node)
      (push-node (make-ast-node "variable-name" name) variable-node)
      (push-node type-node variable-node)
      (push-node (make-ast-node "variable-value" value) variable-node)
      variable-node)))
